protected/controllers/DashboardController.php
<?php

class DashboardController extends Controller {

    public function init() {
        // check if login or not if loggin then go ahead with below methods otherwise ask for login
        if (!isset(Yii::app()->session['wrd_userdata'])) {
            $this->redirect(array('user/login'));
        }
    }

    public function actionIndex() {
        $this->render('index');
    }

    public function actionEditprofile() {

        $request = Yii::app()->request;
        $profiledata = Yii::app()->session['wrd_userdata'];
         
       // if ($request->getPost('uid')) {
            if ($request->getPost('action_edituser')) {
                $arrPostData = array(
                    'uid' => base64_decode($request->getPost('uid')),
                    'state' => $request->getPost('edit_state'),
                    'city' => $request->getPost('edit_city'),
                    'avatar_img' => $request->getPost('edit_avatar'),
                    'created_ip' => $_SERVER['REMOTE_ADDR'],
                );
                $api_obj = new ApiCaller();
                $arrData = $api_obj->sendRequest(array(
                    'controller' => 'user',
                    'action' => 'updateProfile',
                    'postdata' => $arrPostData,
                ));
                Yii::app()->user->setFlash('success', Yii::t('wrd_message', 'editprofile_success'));
                $this->redirect('dashboard/index', array('confirm_data' => $arrData));
            } else {
                $this->render('editprofile',array('profiledata'=>$profiledata));
            }
       // }
    }
    // Uncomment the following methods and override them if needed
    /*
      public function filters()
      {
      // return the filter configuration for this controller, e.g.:
      return array(
      'inlineFilterName',
      array(
      'class'=>'path.to.FilterClass',
      'propertyName'=>'propertyValue',
      ),
      );
      }
     */
    

}

protected/controllers/UserController.php
<?php

class UserController extends Controller {
    
    
    public function actionIndex() {
//        Yii::app()->request->getUrl();
//        if (Yii::app()->request->getParam('uid')) {
//            Yii::app()->user->setFlash('success',  Yii::t('wrd_message', 'LABELSELECTTITLE')); 
//
//            Yii::app()->user->setFlash('success', "Data1 saved!");
//            Yii::app()->user->setFlash('error', "Data2 failed!");
//            Yii::app()->user->setFlash('notice', "Data3 ignored.");
//        }
        $this->render('index');
    }

    public function actionCheckusername() {

        $request = Yii::app()->request;
        if ($request->getPost('action_checkuser')) {
            $arrPostData = array(
                'username' => $request->getPost('action_checkuser'),
            );
            $api_obj = new ApiCaller();
            $arrData = $api_obj->sendRequest(array(
                'controller' => 'user',
                'action' => 'checkAvailability',
                'postdata' => $arrPostData,
            ));
            $data = $arrData->result;
            echo CJSON::encode(array('check_user' => $data));
        } else {
            $this->render('register');
        }
    }

    public function actionRegister() {

        $request = Yii::app()->request;
        if ($request->getPost('action_register')) {
            $arrPostData = array(
                'username' => $request->getPost('reg_username'),
                'password' => $request->getPost('reg_pwd'),
                'parent_email' => $request->getPost('reg_pemail'),
                'avatar_img' => 'default_img.jpg',
                'created_ip' => $_SERVER['REMOTE_ADDR'],
            );
            $api_obj = new ApiCaller();
            $arrData = $api_obj->sendRequest(array(
                'controller' => 'user',
                'action' => 'create',
                'postdata' => $arrPostData,
            ));

            if ($arrData->result->flag == 1) {
                $id = base64_encode($arrData->result->response_data);
                $mail = new JPhpMailer;
                $mail->IsSMTP();
                $mail->SetFrom(Yii::app()->params['FormEmail'], Yii::app()->params['FormName']);
                $mail->Subject = Yii::t('wrd_message', 'reg_mail_subect');
                $mail->MsgHTML('<h1>Dear Parents, <br> Varify link <a href="http://192.168.1.107/worldoo_main/confirmuser/' . $id . '" >Verify</a></h1>');
                $mail->AddAddress($request->getPost('reg_pemail'), 'Parents');
                if (!$mail->Send()) {
                    Yii::app()->user->setFlash('error', Yii::t('wrd_message', 'register_error_mail'));
                    //exit;
                } else {
                    //Yii::app()->user->setFlash('success', Yii::t('wrd_message', 'register_scuccess'));
                    //echo CJSON::encode(array('regis_data' => $arrData));
                    echo CHtml::encode($arrData->result->message, true);

                }
            }
        } else {
            $this->render('register');
        }
    }

    public function actionLogin() {

        $request = Yii::app()->request;
        if ($request->getPost('action_login')) {
            $arrPostData = array(
                'username' => $request->getPost('reg_username'),
                'password' => $request->getPost('reg_pwd'),
            );

            $api_obj = new ApiCaller();
            $arrData = $api_obj->sendRequest(array(
                'controller' => 'user',
                'action' => 'checkLogin',
                'postdata' => $arrPostData,
            ));

            if ($arrData->result->flag == 1) {
                //set session
                Yii::app()->session['wrd_userdata'] = $arrData->result->response_data;
                $this->redirect(array('dashboard/index'));
            } else {
                Yii::app()->user->setFlash('error', Yii::t('wrd_message', 'invalid_login'));
                $this->render('login');
            }
        } else {
            $this->render('login');
        }
    }

    public function actionLogout() {
        //destory all session 
        Yii::app()->session->destroy();
        $this->redirect(array('user/index'));
    }

    public function actionConfirmuser() {

        Yii::app()->request->getUrl();
        if (Yii::app()->request->getParam('uid')) {
            $api_obj = new ApiCaller();
            $uid = base64_decode(Yii::app()->request->getParam('uid'));
            //check parent user already confirm or not
            $arrPostData = array('uid' => $uid);
            $arrData = $api_obj->sendRequest(array(
                    'controller' => 'user',
                    'action' => 'readOneById',
                    'postdata' => $arrPostData,
                ));
            if($arrData->result->response_data->activated == 0){
                $this->render('confirmuser');  // if not activated go to confirm form page
            }else{
                $this->redirect(array('user/login'));  // if activated go to login
            }
        }
        $request = Yii::app()->request;
        if ($request->getPost('uid')) {
            if ($request->getPost('action_confirmuser')) {
                $arrPostData = array(
                    'uid' => base64_decode($request->getPost('uid')),
                    'firstname' => $request->getPost('con_firstname'),
                    'lastname' => $request->getPost('con_lastname'),
                    'state' => $request->getPost('con_state'),
                    'city' => $request->getPost('con_city'),
                    'gender' => $request->getPost('con_gender'),
                    'date_of_birth' => $request->getPost('con_dob'),
                    'created_ip' => $_SERVER['REMOTE_ADDR'],
                );
                $api_obj = new ApiCaller();
                $arrData = $api_obj->sendRequest(array(
                    'controller' => 'user',
                    'action' => 'confirmUser',
                    'postdata' => $arrPostData,
                ));
                Yii::app()->user->setFlash('confirm_success', Yii::t('wrd_message', 'confirm_success'));
                $this->render('confirmuser', array('confirm_data' => $arrData));
            } else {
                $this->render('confirmuser');
            }
        }
    }

    public function actionGeneratexml() {

        $module = new TblUsers();
        $events = $module->getallrecords();

        //below array $url converted into required(sitemap.xml) structure       
        $xmldata = '<?xml version="1.0" encoding="utf-8"?>';
        $xmldata .= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
        $xmldata .= '<users>';

        foreach ($events as $url => $data) {
            $xmldata .= '<user>';
            $xmldata .= '<name>' . $data['name'] . '</name>';
            $xmldata .= '<email>' . $data['email'] . '</email>';
            $xmldata .= '<contact_no>' . $data['contact_no'] . '</contact_no>';
            $xmldata .= '<address>' . $data['address'] . '</address>';
            $xmldata .= '<gender>' . $data['gender'] . '</gender>';
            $xmldata .= '<create_date>' . $data['create_date'] . '</create_date>';
            $xmldata .= '</user>';
        }
        $xmldata .= '</users>';
        $xmldata .= '</urlset>';

        if (file_put_contents('sitemap.xml', $xmldata)) {
            echo "sitemap.xml file created on project root folder..";
        }
    }

}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ 
/*if(Yii::app()->session['wrd_userdata']){
    $sess_data  = Yii::app()->session['wrd_userdata'];
}else{
    $sess_data = array();
}*/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework 
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	
        <!-- JQuery Start Here-->
        <script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/369045e3/jquery.js"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->
        <?php 
        /*if($sess_data->username == ''){
          $login_menu = array('label'=>'Login', 'url'=>array('/user/login'));
        }else{
            $login_menu = array('label'=>'Log out', 'url'=>array('/user/logout'));
        }*/
        ?>
	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('site/index')),
                                array('label'=>'Login', 'url'=>array('user/login')),
                                array('label'=>'Log out', 'url'=>array('user/logout')),
                                array('label'=>'Profile', 'url'=>array('dashboard/editprofile')),
                                
                            
				//array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				//array('label'=>'Contact', 'url'=>array('/site/contact')),
				//array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				//array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>
                
                <?php
// show flash messages  in yii framework Mehul as in 22-1-14
    foreach(Yii::app()->user->getFlashes() as $key => $message) {
        echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
    }
?>
                
	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>